### ISSUE TITLE
[BUG] Opensearch benchmark doesn't find arm64 binary to download

### ISSUE THREAD

**Issue by AGSaidi** [opensearch-project/opensearch-benchmark#109]
**Describe the bug**
Running the following on an arm (Graviton) system fails to find version of elastic search because Opensearch uses `arm64` and the script runs `sysstats.cpu_arch()` which returns `aarch64`

**To Reproduce**
```
opensearch-benchmark execute_test --distribution-version=1.2.4 --workload=geonames
```

**Expected behavior**
The benchmark runs

**Logs**
```
[ERROR] Cannot execute_test. Cannot download OpenSearch distribution from [https://artifacts.opensearch.org/releases/bundle/opensearch/1.0.0/opensearch-1.0.0-linux-aarch64.tar.gz]. Please check that the specified version [1.0.0] is correct.
	Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/osbenchmark/builder/supplier.py", line 536, in fetch
    net.download(download_url, distribution_path, progress_indicator=progress)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/osbenchmark/utils/net.py", line 229, in download
    expected_size_in_bytes = download_http(url, tmp_data_set_path, expected_size_in_bytes, progress_indicator)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/osbenchmark/utils/net.py", line 184, in download_http
    raise urllib.error.HTTPError(url, r.status, "", None, None)
urllib.error.HTTPError: HTTP Error 403:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/osbenchmark/builder/builder.py", line 563, in receiveMsg_StartNodes
    self.builder.start_engine()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/osbenchmark/builder/builder.py", line 678, in start_engine
    binaries = self.supply()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/osbenchmark/builder/supplier.py", line 288, in __call__
    supplier.fetch()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/osbenchmark/builder/supplier.py", line 541, in fetch
    raise exceptions.SystemSetupError("Cannot download OpenSearch distribution from [%s]. Please check that the specified "
osbenchmark.exceptions.SystemSetupError: Cannot download OpenSearch distribution from [https://artifacts.opensearch.org/releases/bundle/opensearch/1.0.0/opensearch-1.0.0-linux-aarch64.tar.gz]. Please check that the specified version [1.0.0] is correct.
```

**More Context (please complete the following information):**
- Workload(Share link for custom workloads): Opensearch-benchmark
- Service(E.g OpenSearch)
- Version (E.g. 1.0)

**Additional context**

The problem happens [here](https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/builder/supplier.py#L265]). 

A fix would be to add the following:
```
self.arch = sysstats.cpu_arch().lower()
if self.arch == "aarch64":
   self.arch = "arm64"
```

or to offer downloads for open search under both the `arm64` and `aarch64` names.

**Comment by achitojha** [comment]
The changed corresponding to this issue have been merged. If you're still facing the issue, feel free to reopen this issue.
