### ISSUE TITLE
[BUG] OpenSearch Benchmark failing to run after installation because of Markupsafe versioning

### ISSUE THREAD

**Issue by travisbenedict** [opensearch-project/opensearch-benchmark#111]
**Describe the bug**
Running OpenSearch Benchmark after a fresh `pip` installation fails because of a `markupsafe` versioning issue. A similar issue can be found here: https://github.com/aws/aws-sam-cli/issues/3661

It looks like MarkupSafe 2.1 was just released yesterday: https://markupsafe.palletsprojects.com/en/2.1.x/changes/

Temporary workaround is to manually install `markupsafe` 2.0.1 after installing OpenSearch Benchmark using `pip install markupsafe==2.0.1`

**To Reproduce**
`pip install opensearch-benchmark`
`opensearch-benchmark list telemetry`

**Expected behavior**
OpenSearch Benchmark should run after being installed.

**Logs**

```
opensearch-benchmark list telemetry
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/3.8.0/bin/opensearch-benchmark", line 5, in <module>
    from osbenchmark.benchmark import main
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/benchmark.py", line 37, in <module>
    from osbenchmark import version, actor, config, paths, \
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/test_execution_orchestrator.py", line 33, in <module>
    from osbenchmark import actor, config, doc_link, \
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/worker_coordinator/__init__.py", line 26, in <module>
    from .worker_coordinator import (
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/worker_coordinator/worker_coordinator.py", line 43, in <module>
    from osbenchmark import actor, config, exceptions, metrics, workload, client, paths, PROGRAM_NAME, telemetry
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/workload/__init__.py", line 25, in <module>
    from .loader import (
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/workload/loader.py", line 33, in <module>
    import jinja2
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/markupsafe/__init__.py)
```

**Comment by travisbenedict** [comment]
Will need to publish a new version of OSB to PyPI for this to take effect
