### ISSUE TITLE
[BUG] OpenSearch Benchmark does not shutdown properly on BulkIndexError from OpenSearch metrics store

### ISSUE THREAD

**Issue by engechas** [opensearch-project/opensearch-benchmark#190]
**Describe the bug**
OpenSearch Benchmark will hang if an exception occurs when running a bulk_index operation against an external metrics store.

Sample exception:
```
elasticsearch.helpers.errors.BulkIndexError: ('5000 document(s) failed to index.', [{'index': {'_index': 'benchmark-metrics-2022-04', '_type': '_doc', '_id': 'fMNSbYABcPwLOkaMtuTa', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': "Number of documents in the index can't exceed [2147483519]

...

During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/thespian/system/actorManager.py", line 178, in _handleOneMessage
    actor_result = self.actorInst.receiveMessage(copy.deepcopy(msg), envelope.sender)

  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/thespian/actors.py", line 838, in receiveMessage
    r = getattr(klass, methodName)(self, message, sender)

  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/worker_coordinator/worker_coordinator.py", line 229, in receiveMsg_BenchmarkFailure
    self.coordinator.close()

  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/worker_coordinator/worker_coordinator.py", line 796, in close
    self.metrics_store.close()

  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/metrics.py", line 434, in close    self.flush()  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/metrics.py", line 830, in flush    self._client.bulk_index(index=self._index, doc_type=OsMetricsStore.METRICS_DOC_TYPE, items=self._docs)  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/metrics.py", line 100, in bulk_index    self.guarded(elasticsearch.helpers.bulk, self._client, items, index=index, chunk_size=5000)  File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/metrics.py", line 178, in guarded    raise exceptions.BenchmarkError(msg)osbenchmark.exceptions.BenchmarkError: An unknown error occurred while running the operation [bulk] against your OpenSearch metrics store on host [redacted] at port [443].
```

**To Reproduce**
Only confirmed method of reproduction is writing against a `benchmark-metrics` index that is full.

**Expected behavior**
The OpenSearch Benchmark processes should terminate.

**More Context (please complete the following information):**
- Version 0.0.1

**Comment by IanHoang** [comment]
@engechas Closing this out due to inactivity. Error doesn't seem related to OSB but rather OS cluster that stores metrics. Feel free to reopen if needed.
