### ISSUE TITLE
[BUG] Docker pipeline fails on RedHat

### ISSUE THREAD

**Issue by gkamat** [opensearch-project/opensearch-benchmark#320]
**Describe the bug**
Docker integration tests fail on RedHat Linux.

**To Reproduce**
```
opensearch-benchmark execute-test --pipeline="docker" --distribution-version="2.5.0" --workload="geonames" --test-mode --target-hosts=127.0.0.1:19200


   ____                  _____                      __       ____                  __                         __
  / __ \____  ___  ____ / ___/___  ____ ___________/ /_     / __ )___  ____  _____/ /_  ____ ___  ____ ______/ /__
 / / / / __ \/ _ \/ __ \\__ \/ _ \/ __ `/ ___/ ___/ __ \   / __  / _ \/ __ \/ ___/ __ \/ __ `__ \/ __ `/ ___/ //_/
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/  /_____/\___/_/ /_/\___/_/ /_/_/ /_/ /_/\__,_/_/  /_/|_|
    /_/

[INFO] Preparing for test execution ...
[ERROR] Cannot execute-test. Docker daemon startup failed with exit code [1]
	Traceback (most recent call last):
  File "/home/ec2-user/opensearch-benchmark/osbenchmark/builder/builder.py", line 563, in receiveMsg_StartNodes
    self.builder.start_engine()
  File "/home/ec2-user/opensearch-benchmark/osbenchmark/builder/builder.py", line 682, in start_engine
    self.nodes = self.launcher.start(self.node_configs)
  File "/home/ec2-user/opensearch-benchmark/osbenchmark/builder/launcher.py", line 54, in start
    self._start_process(binary_path)
  File "/home/ec2-user/opensearch-benchmark/osbenchmark/builder/launcher.py", line 75, in _start_process
    raise exceptions.LaunchError(msg)
osbenchmark.exceptions.LaunchError: Docker daemon startup failed with exit code [1]


```

**Comment by IanHoang** [comment]
@gkamat Is this still an open issue?
