### ISSUE TITLE
[BUG] Running test with Datastore experiences transport error

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#330]
**Describe the bug**
Ran tests last week with an external OpenSearch cluster as OSB datastore and it was successful. However, trying again this week with mainline code (tried with commit  which was the latest commit my mainline had last week). Encountering this issue when trying to using my external OpenSearch cluster as a datastore.
```
osbenchmark.exceptions.BenchmarkError: Error in test execution orchestrator (A transport error occurred while running the operation [put_template] against your OpenSearch metrics store on host [search-opensearch-metrics-l7trprdkndjfbrayqdbkuzdbyi.us-east-1.es.amazonaws.com] at port [443].)
```
Verified that this OpenSearch cluster is green, not out of space, and does not have any write blocks. Will need to try with another cluster. I checked the opensearch-py repository to see if it was an issue with a recently committed change but that doesn't seem to be the case. 

**To Reproduce**
1. Set datastore config
```
[reporting]
datastore.type = opensearch
datastore.host = <ENDPOINT>
datastore.port = 443
datastore.secure = True
datastore.ssl.verification_mode = none
datastore.user = <USERNAME>
datastore.password =  <PASSWORD>
```
2. Run a test: 
```
opensearch-benchmark execute-test --pipeline=benchmark-only --workload=geonames --target-host="<ENDPOINT>" --client-options="basic_auth_user:'<USERNAME>',basic_auth_password:'<PASSWORD>'" --test-mode
```

**Expected behavior**
Should run and ingest metrics into datastore. 

**Logs**
```
2023-06-12 21:04:39,843 ActorAddr-(T|:60117)/PID:10589 osbenchmark.workload.loader INFO Reading workload specification file [/Users/hoangia/.benchmark/benchmarks/workloads/default/geonames/workload.json].
2023-06-12 21:04:39,968 ActorAddr-(T|:60117)/PID:10589 osbenchmark.workload.loader INFO Final rendered workload for '/Users/hoangia/.benchmark/benchmarks/workloads/default/geonames/workload.json' has been written to '/var/folders/yh/89c2pcg10szgzwc6qj2h04gst115h_/T/tmpw2d3fy16.json'.
2023-06-12 21:04:39,977 ActorAddr-(T|:60117)/PID:10589 osbenchmark.workload.loader INFO Loading template [definition for index geonames in index.json].
2023-06-12 21:04:39,982 ActorAddr-(T|:60117)/PID:10589 osbenchmark.utils.modules INFO Loading component [geonames] from [/Users/hoangia/.benchmark/benchmarks/workloads/default/geonames]
2023-06-12 21:04:39,985 ActorAddr-(T|:60117)/PID:10589 osbenchmark.workload.loader INFO Preparing workload [geonames] for test mode.
2023-06-12 21:04:40,47 ActorAddr-(T|:60117)/PID:10589 osbenchmark.client INFO Creating OpenSearch client connected to [{'host': 'search-opensearch-metrics-l7trprdkndjfbrayqdbkuzdbyi.us-east-1.es.amazonaws.com', 'port': '443'}] with options [{'use_ssl': True, 'verify_certs': False, 'timeout': 120, 'basic_auth_user': 'hoangia', 'basic_auth_password': '*****'}]
2023-06-12 21:04:40,48 ActorAddr-(T|:60117)/PID:10589 osbenchmark.client INFO SSL support: on
2023-06-12 21:04:40,58 ActorAddr-(T|:60117)/PID:10589 osbenchmark.client INFO SSL certificate verification: off
2023-06-12 21:04:40,59 ActorAddr-(T|:60117)/PID:10589 osbenchmark.client WARNING User has enabled SSL but disabled certificate verification. This is dangerous but may be ok for a benchmark. Disabling urllib warnings now to avoid a logging storm. See https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings for details.
2023-06-12 21:04:40,59 ActorAddr-(T|:60117)/PID:10589 osbenchmark.client INFO SSL client authentication: off
2023-06-12 21:04:40,59 ActorAddr-(T|:60117)/PID:10589 osbenchmark.client INFO HTTP basic authentication: on
2023-06-12 21:04:40,59 ActorAddr-(T|:60117)/PID:10589 osbenchmark.client INFO HTTP compression: off
2023-06-12 21:04:40,260 ActorAddr-(T|:60117)/PID:10589 osbenchmark.metrics INFO Creating OpenSearch metrics store
2023-06-12 21:04:40,261 ActorAddr-(T|:60117)/PID:10589 osbenchmark.metrics INFO Opening metrics store for test execution timestamp=[20230612T210438Z], workload=[geonames],test_procedure=[append-no-conflicts], provision_config_instance=[['external']]
2023-06-12 21:04:40,356 ActorAddr-(T|:60117)/PID:10589 osbenchmark.metrics ERROR A transport error occurred while running the operation [put_template] against your OpenSearch metrics store on host [search-opensearch-metrics-l7trprdkndjfbrayqdbkuzdbyi.us-east-1.es.amazonaws.com] at port [443].
Traceback (most recent call last):

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/metrics.py", line 120, in guarded
    return target(*args, **kwargs)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/client/indices.py", line 631, in put_template
    return self.transport.perform_request(

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/transport.py", line 412, in perform_request
    raise e

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/transport.py", line 373, in perform_request
    status, headers_response, data = connection.perform_request(

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 282, in perform_request
    self._raise_error(response.status, raw_data)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(

opensearchpy.exceptions.RequestError: RequestError(400, 'invalid_index_template_exception', 'index_template [benchmark-metrics] invalid, cause [Validation Failed: 1: expected total copies needs to be a multiple of total awareness attributes [3];]')

2023-06-12 21:04:40,364 ActorAddr-(T|:60117)/PID:10589 osbenchmark.actor ERROR Error in test execution orchestrator
Traceback (most recent call last):

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/metrics.py", line 120, in guarded
    return target(*args, **kwargs)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/client/indices.py", line 631, in put_template
    return self.transport.perform_request(

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/transport.py", line 412, in perform_request
    raise e

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/transport.py", line 373, in perform_request
    status, headers_response, data = connection.perform_request(

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 282, in perform_request
    self._raise_error(response.status, raw_data)

  File "/Users/hoangia/.pyenv/versions/3.8.12/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(

opensearchpy.exceptions.RequestError: RequestError(400, 'invalid_index_template_exception', 'index_template [benchmark-metrics] invalid, cause [Validation Failed: 1: expected total copies needs to be a multiple of total awareness attributes [3];]')


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/actor.py", line 92, in guard
    return f(self, msg, sender)

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/test_execution_orchestrator.py", line 108, in receiveMsg_Setup
    self.coordinator.setup(sources=msg.sources)

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/test_execution_orchestrator.py", line 210, in setup
    self.metrics_store = metrics.metrics_store(

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/metrics.py", line 285, in metrics_store
    store.open(

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/metrics.py", line 804, in open
    self._client.put_template("benchmark-metrics", self._get_template())

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/metrics.py", line 74, in put_template
    return self.guarded(self._client.indices.put_template, name=name, body=template)

  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/metrics.py", line 164, in guarded
    raise exceptions.BenchmarkError(msg)

osbenchmark.exceptions.BenchmarkError: A transport error occurred while running the operation [put_template] against your OpenSearch metrics store on host [search-opensearch-metrics-l7trprdkndjfbrayqdbkuzdbyi.us-east-1.es.amazonaws.com] at port [443].

2023-06-12 21:04:40,383 ActorAddr-(T|:60117)/PID:10589 osbenchmark.actor INFO BenchmarkActor received unknown message [ActorExitRequest] (ignoring).
2023-06-12 21:04:43,388 -not-actor-/PID:10553 osbenchmark.benchmark INFO Attempting to shutdown internal actor system.
2023-06-12 21:04:43,391 -not-actor-/PID:10588 root INFO ActorSystem Logging Shutdown
2023-06-12 21:04:43,415 -not-actor-/PID:10553 osbenchmark.benchmark INFO Actor system is still running. Waiting...
2023-06-12 21:04:43,414 -not-actor-/PID:10587 root INFO ---- Actor System shutdown
2023-06-12 21:04:44,417 -not-actor-/PID:10553 osbenchmark.benchmark INFO Shutdown completed.
2023-06-12 21:04:44,418 -not-actor-/PID:10553 osbenchmark.benchmark ERROR Cannot run subcommand [execute-test].
Traceback (most recent call last):
  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/benchmark.py", line 908, in dispatch_sub_command
    execute_test(cfg, args.kill_running_processes)
  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/benchmark.py", line 676, in execute_test
    with_actor_system(test_execution_orchestrator.run, cfg)
  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/benchmark.py", line 703, in with_actor_system
    runnable(cfg)
  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/test_execution_orchestrator.py", line 379, in run
    raise e
  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/test_execution_orchestrator.py", line 376, in run
    pipeline(cfg)
  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/test_execution_orchestrator.py", line 69, in __call__
    self.target(cfg)
  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/test_execution_orchestrator.py", line 314, in benchmark_only
    return execute_test(cfg, external=True)
  File "/Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark/osbenchmark/test_execution_orchestrator.py", line 273, in execute_test
    raise exceptions.BenchmarkError(result.message, result.cause)
osbenchmark.exceptions.BenchmarkError: Error in test execution orchestrator (A transport error occurred while running the operation [put_template] against your OpenSearch metrics store on host [search-opensearch-metrics-l7trprdkndjfbrayqdbkuzdbyi.us-east-1.es.amazonaws.com] at port [443].)
```

**More Context (please complete the following information):**
- Workload(Share link for custom workloads): Geonames
- Service(E.g OpenSearch): OpenSearch 2.5 for Datastore OpenSearch Cluster
- Version (E.g. 1.0): OSB v1.0.0

**Additional context**

**Comment by IanHoang** [comment]
Currently implemented the datastore.number_of_shards and datastore.number_of_replicas options. I've tested it out but there seems to be some blockers with opensearch-py that I'm facing. See the following for testing setup:

### Single Node Cluster with 1AZ
Datastore config set `number_of_shards = 9` and `number_of_replicas = 1`
After OSB creates index
```
health status index                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   benchmark-metrics-2023-06         9JB1Ua3DRvW99DwokDyziA   9   1        280            0    779.2kb        779.2kb
yellow open   benchmark-results-2023-06         hhIrNV3KR4C7_kXS0_hkqg   9   1        184            0    152.3kb        152.3kb
yellow open   benchmark-test-executions-2023-06 0Kt0nFtJSTmHJ5llmjMIYA   9   1         27            0     57.6kb         57.6kb
```

Datastore config set `number_of_shards = 9` and `number_of_replicas = 2`
After OSB creates indices
```
health status index                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   benchmark-metrics-2023-06         4-paEcf-QLGWnufInLRaLA   9   2        280            0    828.9kb        828.9kb
yellow open   benchmark-results-2023-06         CJ_Zz5uFTUSuZkNxe5MRAQ   9   2        184            0    151.5kb        151.5kb
yellow open   benchmark-test-executions-2023-06 yv4zLZNNSZyYPmUJdRaQDg   9   2          1            0     11.3kb         11.3kb
```

### Multi Node Cluster (3M3D) with 3AZs
Datastore config set `number_of_shards = 9` and `number_of_replicas = 2`
After OSB creates indices
```
health status index                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   benchmark-metrics-2023-06         QdA3AnHMS8iNfGk7da3ZZA   9   2        280            0      1.8mb        642.6kb
green  open   benchmark-results-2023-06         J6RPQNX4Tm2kmCdyslEh9Q   9   2        184            0    457.5kb        152.4kb
green  open   benchmark-test-executions-2023-06 0TnVfDN1TNeaefIQ_0DKLw   9   2         27            0    147.2kb         44.7kb
```
Datastore config set `number_of_shards = 9` and `number_of_replicas = 1`
OSB encounters an error due to OpenSearch-Py
```
opensearchpy.exceptions.RequestError: RequestError(400, 'invalid_index_template_exception', 'index_template [benchmark-metrics] invalid, cause [Validation Failed: 1: expected total copies needs to be a multiple of total awareness attributes [3];]')
```

To find the total copies, we use `number of copies in cluster = number_of_shards * (number_of_replicas + 1)`. This should technically work since datastore config with `number_of_shards = 9` and `number_of_replicas = 1` would create 18 number of copies in the cluster, which is a multiple of 3. 
```
# 18 total copies in the cluster and is a multiple of 3
9 * (1+1) = 18
```

**Comment by IanHoang** [comment]
Opened an issue with OpenSearch-Py https://github.com/opensearch-project/opensearch-py/issues/411

**Comment by dblock** [comment]
It doesn't look like an issue with the client.

**Comment by IanHoang** [comment]
Was able to test a little more and was able to get OSB to work with a multi node datastore with 3AZs (3 awareness attributes).
```
health status index                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   benchmark-metrics-2023-06         KFoeSRyTSASgMMJT7lUM9Q   9   2        280            0      1.9mb        606.3kb
green  open   benchmark-results-2023-06         oih88lC5RA6kj1Y7GxQXHw   9   2        184            0    504.8kb        190.2kb
green  open   benchmark-test-executions-2023-06 IU_a8jO1TPSI8r9-gzbI4Q   9   2          1            0     34.3kb         11.3kb
green  open   .kibana_1                         07gfCKy8S6WlaI14ow-LdQ   1   2          0            0       624b           208b
green  open   .opendistro_security              AQd7Sp4_QmeYAQkzDFw6AA   1   2         10            4    218.6kb         74.4kb
```
In the previous multi node datastore, the only difference was the setting:
```
      "default_number_of_replicas" : "2",
          "number_of_replicas" : "1",
          "number_of_replicas" : "1",
```
Suspect that this might be the cause. Will work on debugging this further.

**Comment by IanHoang** [comment]
This is an implementation detail: In this situation, the transport error was caused by replica configuration in the cluster. This error occurs due to cluster configuration detail. We will create a separate issue to make sure OSB throws a more descriptive error message when encountering transport errors.
