### ISSUE TITLE
[BUG] Sleep runner is failed to complete due to missing client_request_start

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-benchmark#485]
**Describe the bug**
BenchmarkError is being raised for sleep operation .

**To Reproduce**
Add following item to schedule, and execute procedure.

```
       {
          "operation": {
            "name": "wait-in-seconds-after-index", 
            "operation-type": "sleep",
            "duration": 2
          }
        },
 ```

**Expected behavior**
Sleep operation should succeed.

**Logs**
If applicable, add logs to help explain your problem.

```
Running delete-target-index                                                    [100% done]
Running create-target-index                                                    [100% done]
Running wait-in-seconds-after-create-index                                     [  0% done]
[ERROR] Cannot execute-test. Error in load generator [0]
        Cannot run task [wait-in-seconds-after-create-index]: 'client_request_start'

```

Log
```

  File "/Users/balasvij/PycharmProjects/knn/opensearch-benchmark/osbenchmark/worker_coordinator/worker_coordinator.py", line 1592, in __call__
    request_start = request_context.request_start

  File "/Users/balasvij/PycharmProjects/knn/opensearch-benchmark/osbenchmark/client.py", line 54, in request_start
    return self.ctx["request_start"]

KeyError: 'request_start'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/balasvij/PycharmProjects/knn/opensearch-benchmark/osbenchmark/worker_coordinator/worker_coordinator.py", line 1595, in __call__
    client_request_end = request_context.client_request_end

  File "/Users/balasvij/PycharmProjects/knn/opensearch-benchmark/osbenchmark/client.py", line 70, in __aexit__
    client_request_start = self.client_request_start

  File "/Users/balasvij/PycharmProjects/knn/opensearch-benchmark/osbenchmark/client.py", line 62, in client_request_start
    return self.ctx["client_request_start"]

KeyError: 'client_request_start'

```

**More Context (please complete the following information):**
Any workload on OpenSearch 2.x/1.x

**Additional context**
Link to source code  https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/worker_coordinator/runner.py#L1666

**Comment by gkamat** [comment]
We need to go through all the client API calls and ensure this issue is fixed everywhere.
