### ISSUE TITLE
[BUG] Unable to run opensearch-benchmark on OSX

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/opensearch-benchmark#89]
**Describe the bug**
I followed https://github.com/opensearch-project/OpenSearch-Benchmark/blob/main/DEVELOPER_GUIDE.md to run the benchmark locally and it failed with following error (logs attached):

```
[ERROR] Cannot execute_test. This test_execution ended with a fatal crash.
```

**To Reproduce**
- Checkout opensearch-benchmark on OSX.
- Setup all the prereq in Developer Guide linked above.
- execute `make prereq` 
- execute `make install`
- `source .venv/bin/activate`
- Run the benchmark test. sample command: ```opensearch-benchmark execute_test --workload=eventdata --target-hosts=endpoint --pipeline=benchmark-only --workload-params="number_of_replicas:1" --client-options="use_ssl:true,basic_auth_user:USERNAME,basic_auth_password:PASSWORD,verify_certs:false" --kill-running-processes```

**Expected behavior**
Benchmark test should execute successfully.

**Logs**
[osx-log.txt](https://github.com/opensearch-project/opensearch-benchmark/files/7717058/osx-log.txt)

**Additional info**
- I verified that there are no listener on 1900 port using `lsof -P -n -r 1 -i :1900`
- I also tried restarting Mac but it didn't help.
- I see the following error in the logs . Not sure if there is any alternative.

 ```
2021-12-15 04:29:48,233 -not-actor-/PID:35422 osbenchmark.actor ERROR Could not initialize internal actor system.
Traceback (most recent call last):
  File "/Volumes/ws/opensearch-benchmark/osbenchmark/actor.py", line 254, in bootstrap_actor_system
    return thespian.actors.ActorSystem(system_base,
  File "/Volumes/ws/opensearch-benchmark/.venv/lib/python3.8/site-packages/thespian/actors.py", line 635, in __init__
    systemBase = self._startupActorSys(
  File "/Volumes/ws/opensearch-benchmark/.venv/lib/python3.8/site-packages/thespian/actors.py", line 676, in _startupActorSys
    systemBase = sbc(self, logDefs=logDefs)
  File "/Volumes/ws/opensearch-benchmark/.venv/lib/python3.8/site-packages/thespian/system/multiprocTCPBase.py", line 28, in __init__
    super(ActorSystemBase, self).__init__(system, logDefs)
  File "/Volumes/ws/opensearch-benchmark/.venv/lib/python3.8/site-packages/thespian/system/multiprocCommon.py", line 86, in __init__
    super(multiprocessCommon, self).__init__(system, logDefs)
  File "/Volumes/ws/opensearch-benchmark/.venv/lib/python3.8/site-packages/thespian/system/systemBase.py", line 326, in __init__
    self._startAdmin(self.adminAddr,
  File "/Volumes/ws/opensearch-benchmark/.venv/lib/python3.8/site-packages/thespian/system/multiprocCommon.py", line 114, in _startAdmin
    raise InvalidActorAddress(adminAddr,
thespian.actors.InvalidActorAddress: ActorAddr-(T|:1900) is not a valid ActorSystem admin```

**Comment by travisbenedict** [comment]
I was able to reproduce this error by running a test while connected to a VPN. When I disconnected from the VPN I was able to successfully run a test. Does that solution work for you?

I'll update the troubleshooting section in the developer guide to be more thorough: https://github.com/opensearch-project/opensearch-benchmark/blob/main/DEVELOPER_GUIDE.md#troubleshooting

**Comment by ankitkala** [comment]
I tried without VPN but then also it failed. [logs](https://github.com/opensearch-project/opensearch-benchmark/files/7728437/osxlogs.txt)

**Comment by dtaivpp** [comment]
Hey all, I also am experiencing this. Even further I am not even able to get a development environment on an M1 Macbook to start debugging because of issues with pyenv.
